# Generated by Django 5.0 on 2024-01-19 08:29

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pythonDev', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Новая страница', max_length=20)),
                ('header_name', models.CharField(default='СТРАНИЦА', max_length=20)),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(default='Новая страница')),
            ],
        ),
        migrations.DeleteModel(
            name='IndexPage',
        ),
    ]
