# Generated by Django 5.0 on 2024-01-19 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pythonDev', '0003_page_url_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='url_name',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
