# Generated by Django 5.0 on 2024-01-19 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pythonDev', '0004_alter_page_url_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Page',
            new_name='PageContent',
        ),
    ]
